### ISSUE TITLE
Error opening necessary plugin libraries

### ISSUE THREAD

**Issue by jasonhallen** [gesellkammer/csoundengine#1]
Hello,

I was able to install csoundengine on my MacBook Pro (macOS 13.5.1) today and successfully import it in Python.  However, when I create an `Engine()` I get the following error:

```
>>> from csoundengine import *
>>> engine = Engine()
Asked for backend sr, but backend pa_cb, does nothave a fixed sr. Using sr=44100

error: syntax error, unexpected T_IDENT  (token "dict_new")
 line 14:
 >>> gi__soundfontIndexes dict_new <<<
Unexpected untyped word gi__soundfontIndexes when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
Error compiling base orchestra. A copy of the orchestra has been saved to /var/folders/lr/q0m4k0hx34q16lqv0x138d980000gn/T/csoundengine-lshfzgse.orc
```

When I run `csound -z` in the command line I don't see `dict_new` in the list.  At the bottom of the opcodes list printout I see these warnings:

```
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libjsfx.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libpathtools.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libelse.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libbeosc.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libcsound_webserver.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/librisset.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libklib.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libsndmeta.dylib' (-1)
WARNING: could not open library '/Users/hallenj/Library/csound/6.0/plugins64/libpoly.dylib' (-1)
```

Csound clearly knows to look in this directory and load the libraries, but apparently it can't open them.  Is this a permissions issue?  Do you have any suggestions for what I could try?

Thanks!
Jason

**Comment by gesellkammer** [comment]
This is a known issue regarding permissions in macos. I haven't yet figured out an efficient way of signing plugins within google actions (which is what is used to build binaries for mac and windows). It is also not easy to test, since the plugins are loaded correctly on google actions.

**Comment by jasonhallen** [comment]
This is strange because a year ago Csound was able to load Michael Gogins' libcsound_webserver.dylib from this directory on the same computer.  Has it been a recent macOS issue that is causing this problem?

**Comment by jasonhallen** [comment]
Do you know of a workaround for this, or does this mean I won't be able to use csoundengine on my Mac until this is resolved?

**Comment by gesellkammer** [comment]
One can authorize a dylib from the finder via right click, I am told. Code
signing needs a developer I'd, which costs 100$ and is not something I am
willing to do right now. In general supporting macos (and the transition to
arm64) has become a real pain.

If you install the plugins via risset, risset has grown the feature to code
sign the downloaded binaries locally.

**Comment by jasonhallen** [comment]
Opening the dylibs with a right click solved the problem for me.  Thanks for your help!
